# APPLICATION
spring.application.name=API
server.port=8443

# DATABASE CONFIG (local overrides)
#change DB variables to the user and password you grantnoed database priveleges to
spring.datasource.url=jdbc:mysql://localhost:3306/safe_dispatch_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
